name: energy-market-analysis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - pip
  - jupyterlab
  - pip:
      - entsoe-py
      - cdsapi>=0.7
      - python-dotenv
      - xarray
      - netcdf4
      - dask
      - pyarrow
      - matplotlib
      - polars
